### PR TITLE
Add initial PHP support

### PR DESCRIPTION
**Pull request by przepompownia**

### CODE REVIEW

**Comment by przepompownia** [comment]
Hi @AckslD 
thank you for creating a promising and fast revJ successor!

**Comment by przepompownia** [comment]
Sample code on which I manually tested it:
```php
<?php

function x($a, $b, $c)
{
    list($a, $b) = [1, 2];
}

x(1, 2, 3);

class X
{
    public function __construct($x, $y)
    {
    }
}

new X(1, 2);
```

**Comment by AckslD** [comment]
Very nice @przepompownia! :heart: Hope it works well for you and glad you like it :)

I really should add some tests in the CI soon but just haven't found the time yet.

**Comment by przepompownia** [comment]
It's noticeably faster than revJ and free from external dependencies. Currently I have no knowledge about treesitter but existing examples helped me finding places where some names are defined and its analogues for PHP.

**Pull request merged**
